### ISSUE TITLE
User Story #1

### ISSUE THREAD

**Issue by nfretz** [nfretz/ICT-129-Demo-2023#2]
As a student, I want get a copy of Nolan's project so that I can save time by not building it from scratch.
< Provide detail as needed >

## Definition of Ready:

- [ ] User story is small enough to be finished within one sprint
- [ ] User story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] Integration tests have been run successfully 
- [ ] Documentation has been updated
- [ ] Release notes have been updated

## Tasks 

- [ ] Get Github account 
- [ ] Clone Nolan's repository  https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository
- [ ] Copy Nolan's project  https://docs.github.com/en/issues/planning-and-tracking-with-projects/creating-projects/copying-an-existing-project
