### ISSUE TITLE
Get github set up

### ISSUE THREAD

**Issue by nfretz** [nfretz/ICT-129-Demo-2023#3]
As a student in ICT 129, I want copy Nolan's github stuff so that I don't have to spend time creating it from scratch.
cuz I'm lazy.

## Acceptance Criteria 

- [ ] I can add a user story to my project
- [ ] Everybody else on the team gets their set of user stories updated when I add one.

## Definition of Ready:

- [x] User story is small enough to be finished within one sprint
- [ ] User story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] Integration tests have been run successfully 
- [ ] Documentation has been updated
- [ ] Release notes have been updated

## Tasks 

- [ ] Get a github account
- [ ] Clone the repository  https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository
- [ ] Copy the project https://docs.github.com/en/issues/planning-and-tracking-with-projects/creating-projects/copying-an-existing-project
