### ISSUE TITLE
A quick  title

### ISSUE THREAD

**Issue by nfretz** [nfretz/ICT-129-Demo-2023#7]
As a student I want to use Github to manage stories so that I can share them with Nolan

## Acceptance Criteria 

- [ ] Nolan is able to see our user stories.
- [ ] Test #2

## Definition of Ready:

- [ ] User story is small enough to be finished within one sprint
- [ ] User story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] Integration tests have been run successfully 
- [ ] Documentation has been updated
- [ ] Release notes have been updated

## Tasks 

- [ ] Make some issues
- [ ] Add Nolan as a contributor
